version: "3.8"

services:
  mysql:
    image: mysql:8.0.25
    cap_add:
      - SYS_NICE
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_DATABASE: okan_yohou
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/my.cnf:/etc/my.cnf
      - ./mysql/data:/var/lib/mysql
    networks:
      - backend_server

  api:
    build:
      context: ./app
      dockerfile: ./build/api/local.Dockerfile
    restart: always
    ports:
      - 8080:8080
    environment:
      REST_PORT: 8080
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: okan_yohou
    env_file:
      - .env
    volumes:
      - ./app:/go/src/app
    depends_on:
      - mysql
    networks:
      - backend_server

networks:
  backend_server:
