// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/Khmer495/okan_yohou/internal/pkg/ent/alert"
	"github.com/Khmer495/okan_yohou/internal/pkg/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	alertMixin := schema.Alert{}.Mixin()
	alertMixinFields1 := alertMixin[1].Fields()
	_ = alertMixinFields1
	alertFields := schema.Alert{}.Fields()
	_ = alertFields
	// alertDescCreatedAt is the schema descriptor for created_at field.
	alertDescCreatedAt := alertMixinFields1[0].Descriptor()
	// alert.DefaultCreatedAt holds the default value on creation for the created_at field.
	alert.DefaultCreatedAt = alertDescCreatedAt.Default.(func() time.Time)
	// alertDescUpdatedAt is the schema descriptor for updated_at field.
	alertDescUpdatedAt := alertMixinFields1[1].Descriptor()
	// alert.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	alert.DefaultUpdatedAt = alertDescUpdatedAt.Default.(func() time.Time)
	// alert.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	alert.UpdateDefaultUpdatedAt = alertDescUpdatedAt.UpdateDefault.(func() time.Time)
}
