// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.2 DO NOT EDIT.
package openapi

// Defines values for AlertTriggerArpress.
const (
	AlertTriggerArpressN1 AlertTriggerArpress = 1

	AlertTriggerArpressN2 AlertTriggerArpress = 2

	AlertTriggerArpressN3 AlertTriggerArpress = 3
)

// Defines values for AlertTriggerFeeltmp.
const (
	AlertTriggerFeeltmpN1 AlertTriggerFeeltmp = 1

	AlertTriggerFeeltmpN2 AlertTriggerFeeltmp = 2

	AlertTriggerFeeltmpN3 AlertTriggerFeeltmp = 3
)

// Defines values for AlertTriggerRhum.
const (
	AlertTriggerRhumN1 AlertTriggerRhum = 1

	AlertTriggerRhumN2 AlertTriggerRhum = 2

	AlertTriggerRhumN3 AlertTriggerRhum = 3
)

// Defines values for AlertTriggerWndspd.
const (
	AlertTriggerWndspdN1 AlertTriggerWndspd = 1

	AlertTriggerWndspdN2 AlertTriggerWndspd = 2

	AlertTriggerWndspdN3 AlertTriggerWndspd = 3
)

// Defines values for AlertTriggerWx.
const (
	AlertTriggerWxN1 AlertTriggerWx = 1

	AlertTriggerWxN2 AlertTriggerWx = 2

	AlertTriggerWxN3 AlertTriggerWx = 3

	AlertTriggerWxN4 AlertTriggerWx = 4

	AlertTriggerWxN5 AlertTriggerWx = 5
)

// Alert defines model for Alert.
type Alert struct {
	Id       *string `json:"id,omitempty"`
	Location *struct {
		// 緯度
		Lat *float32 `json:"lat,omitempty"`

		// 経度
		Lon *float32 `json:"lon,omitempty"`
	} `json:"location,omitempty"`

	// 通知内容
	Text    *string `json:"text,omitempty"`
	Title   *string `json:"title,omitempty"`
	Trigger *struct {
		// 気圧: `1` - 高気圧 `2` - 通常 `3` - 低気圧
		Arpress *AlertTriggerArpress `json:"arpress"`

		// 体感気温: `1` - ？ `2` - ？ `3` - ？
		Feeltmp *AlertTriggerFeeltmp `json:"feeltmp"`

		// 湿度: `1` - ？ `2` - ？ `3` - ？
		Rhum *AlertTriggerRhum `json:"rhum"`

		// 気温
		Temp *float32 `json:"temp,omitempty"`

		// 風速: `1` - ？ `2` - ？ `3` - ？
		Wndspd *AlertTriggerWndspd `json:"wndspd"`

		// 天気: `1` - 晴 `2` - 曇 `3` - 雨 `4` - 雷 `5` - 雪
		Wx *AlertTriggerWx `json:"wx"`
	} `json:"trigger,omitempty"`
}

// 気圧: `1` - 高気圧 `2` - 通常 `3` - 低気圧
type AlertTriggerArpress int

// 体感気温: `1` - ？ `2` - ？ `3` - ？
type AlertTriggerFeeltmp int

// 湿度: `1` - ？ `2` - ？ `3` - ？
type AlertTriggerRhum int

// 風速: `1` - ？ `2` - ？ `3` - ？
type AlertTriggerWndspd int

// 天気: `1` - 晴 `2` - 曇 `3` - 雨 `4` - 雷 `5` - 雪
type AlertTriggerWx int

// PostAlertsJSONBody defines parameters for PostAlerts.
type PostAlertsJSONBody Alert

// PutAlertsAlertIdJSONBody defines parameters for PutAlertsAlertId.
type PutAlertsAlertIdJSONBody Alert

// PostAlertsJSONRequestBody defines body for PostAlerts for application/json ContentType.
type PostAlertsJSONRequestBody PostAlertsJSONBody

// PutAlertsAlertIdJSONRequestBody defines body for PutAlertsAlertId for application/json ContentType.
type PutAlertsAlertIdJSONRequestBody PutAlertsAlertIdJSONBody

