// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.2 DO NOT EDIT.
package openapi

// Alert defines model for Alert.
type Alert struct {
	// 気圧: `1` - 高気圧 `2` - 通常 `3` - 低気圧
	Arpress *int `json:"arpress,omitempty"`

	// 体感気温: `1` - ？ `2` - ？ `3` - ？
	Feeltmp *int   `json:"feeltmp,omitempty"`
	Id      string `json:"id"`

	// 緯度
	Lat float64 `json:"lat"`

	// 経度
	Lon float64 `json:"lon"`

	// 湿度: `1` - ？ `2` - ？ `3` - ？
	Rhum *int `json:"rhum,omitempty"`

	// 気温
	Temp *float64 `json:"temp,omitempty"`

	// 通知内容
	Text  string `json:"text"`
	Title string `json:"title"`

	// 風速: `1` - ？ `2` - ？ `3` - ？
	Wndspd *int `json:"wndspd,omitempty"`

	// 天気: `1` - 晴 `2` - 曇 `3` - 雨 `4` - 雷 `5` - 雪
	Wx *int `json:"wx,omitempty"`
}

// GetAlertsParams defines parameters for GetAlerts.
type GetAlertsParams struct {
	// ページ数
	Page *int `json:"page,omitempty"`

	// 1ページあたりの上限数
	Limit *int `json:"limit,omitempty"`
}

// PostAlertsJSONBody defines parameters for PostAlerts.
type PostAlertsJSONBody struct {
	// 気圧: `1` - 高気圧 `2` - 通常 `3` - 低気圧
	Arpress *int `json:"arpress,omitempty"`

	// 体感気温: `1` - ？ `2` - ？ `3` - ？
	Feeltmp *int `json:"feeltmp,omitempty"`

	// 緯度
	Lat float64 `json:"lat"`

	// 経度
	Lon float64 `json:"lon"`

	// 湿度: `1` - ？ `2` - ？ `3` - ？
	Rhum *int `json:"rhum,omitempty"`

	// 気温
	Temp *float64 `json:"temp,omitempty"`

	// 通知内容
	Text  string `json:"text"`
	Title string `json:"title"`

	// 風速: `1` - ？ `2` - ？ `3` - ？
	Wndspd *int `json:"wndspd,omitempty"`

	// 天気: `1` - 晴 `2` - 曇 `3` - 雨 `4` - 雷 `5` - 雪
	Wx *int `json:"wx,omitempty"`
}

// PutAlertsAlertIdJSONBody defines parameters for PutAlertsAlertId.
type PutAlertsAlertIdJSONBody struct {
	// 気圧: `1` - 高気圧 `2` - 通常 `3` - 低気圧
	Arpress *int `json:"arpress,omitempty"`

	// 体感気温: `1` - ？ `2` - ？ `3` - ？
	Feeltmp *int `json:"feeltmp,omitempty"`

	// 緯度
	Lat *float64 `json:"lat,omitempty"`

	// 経度
	Lon *float64 `json:"lon,omitempty"`

	// 湿度: `1` - ？ `2` - ？ `3` - ？
	Rhum *int `json:"rhum,omitempty"`

	// 気温
	Temp *float64 `json:"temp,omitempty"`

	// 通知内容
	Text  *string `json:"text,omitempty"`
	Title *string `json:"title,omitempty"`

	// 風速: `1` - ？ `2` - ？ `3` - ？
	Wndspd *int `json:"wndspd,omitempty"`

	// 天気: `1` - 晴 `2` - 曇 `3` - 雨 `4` - 雷 `5` - 雪
	Wx *int `json:"wx,omitempty"`
}

// PostAlertsJSONRequestBody defines body for PostAlerts for application/json ContentType.
type PostAlertsJSONRequestBody PostAlertsJSONBody

// PutAlertsAlertIdJSONRequestBody defines body for PutAlertsAlertId for application/json ContentType.
type PutAlertsAlertIdJSONRequestBody PutAlertsAlertIdJSONBody

