// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AlertsColumns holds the columns for the "alerts" table.
	AlertsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "ulid", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "title", Type: field.TypeString},
		{Name: "lat", Type: field.TypeFloat64},
		{Name: "lon", Type: field.TypeFloat64},
		{Name: "wx", Type: field.TypeInt, Nullable: true},
		{Name: "temp", Type: field.TypeFloat64, Nullable: true},
		{Name: "arpress", Type: field.TypeInt, Nullable: true},
		{Name: "wndspd", Type: field.TypeInt, Nullable: true},
		{Name: "rhum", Type: field.TypeInt, Nullable: true},
		{Name: "feeltmp", Type: field.TypeInt, Nullable: true},
		{Name: "text", Type: field.TypeString},
	}
	// AlertsTable holds the schema information for the "alerts" table.
	AlertsTable = &schema.Table{
		Name:       "alerts",
		Columns:    AlertsColumns,
		PrimaryKey: []*schema.Column{AlertsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AlertsTable,
	}
)

func init() {
}
